export default [
	'{{return undefined->isString->toString = "false"}}',
	'{{return null->isString->toString = "false"}}',
	'{{return true->isString->toString = "false"}}',
	'{{return false->isString->toString = "false"}}',
	'{{return 10->isString->toString = "false"}}',
	'{{return /regexp/->isString->toString = "false"}}',
	'{{return getDate->isString->toString = "false"}}',
	'{{return global->isString->toString = "false"}}',
	'{{return [1, 2, 3]->isString->toString = "false"}}',
	'{{return (=>10)->isString->toString = "false"}}',
	'{{return "string"[0] = "s"}}',
	'{{return "string"[-1] = "g"}}',
	'{{return "string"[6]->isUndefined->toString = "true"}}',
	'{{return "string"[300]->isUndefined->toString = "true"}}',
	'{{return "string"[-7]->isUndefined->toString = "true"}}',
	'{{return "string"[-300]->isUndefined->toString = "true"}}',
	'{{return "string"["0"] = "s"}}',
	'{{return "string"["-1"] = "g"}}',
	'{{return "string"[true] = "t"}}',
	'{{return "string"[false] = "s"}}',
	'{{return "string"["0x00"] = "s"}}',
	'{{return "string"["0x01"] = "t"}}',
	'{{return "string"["0b00"] = "s"}}',
	'{{return "string"["0b01"] = "t"}}',
	'{{return "string"["0b10"] = "r"}}',
	'{{return "string"["0b11"] = "i"}}',
	'{{return "string"[UNDEFINED]->isUndefined->toString = "true"}}',
	'{{return "string"[null]->isUndefined->toString = "true"}}',
	'{{return "string"[[1, 2, 3]]->isUndefined->toString = "true"}}',
	'{{return "string"[getDate]->isUndefined->toString = "true"}}',
	'{{return "string"->isString->toString = "true"}}',
	'{{return "string"->toString = "string"}}',
	'{{return "0x32"->toNumber = 50}}',
	'{{return "+0x32"->toNumber = 50}}',
	'{{return "-0x32"->toNumber = -50}}',
	'{{return "0X32"->toNumber = 50}}',
	'{{return "+0X32"->toNumber = 50}}',
	'{{return "-0X32"->toNumber = -50}}',
	'{{return "0b110010"->toNumber = 50}}',
	'{{return "+0b110010"->toNumber = 50}}',
	'{{return "-0b110010"->toNumber = -50}}',
	'{{return "0B110010"->toNumber = 50}}',
	'{{return "+0B110010"->toNumber = 50}}',
	'{{return "-0B110010"->toNumber = -50}}',
	'{{return "10"->toNumber = 10}}',
	'{{return "-10"->toNumber = -10}}',
	'{{return "-10"->toNumber = -10}}',
	'{{return ".32"->toNumber = 0.32}}',
	'{{return "0.32"->toNumber = .32}}',
	'{{return "17.32"->toNumber = 17.32}}',
	'{{return "+.32"->toNumber = 0.32}}',
	'{{return "+0.32"->toNumber = .32}}',
	'{{return "+17.32"->toNumber = 17.32}}',
	'{{return "-.32"->toNumber = -0.32}}',
	'{{return "-0.32"->toNumber = -.32}}',
	'{{return "-17.32"->toNumber = -17.32}}',
	'{{return "-17.32"->toBoolean->toString = "true"}}',
	'{{return "0"->toBoolean->toString = "true"}}',
	'{{return ""->toBoolean->toString = "false"}}',
	'{{return ""->toJSON = "\\"\\""}}',
	'{{return "FOO"->toJSON = "\\"FOO\\""}}',
	'{{return "FOO"->length = 3}}',
	'{{return ""->length = 0}}',
	'{{return "FOOBAR"->toLowerCase = "foobar"}}',
	'{{return "FooBar"->toLowerCase = "foobar"}}',
	'{{return "foobar"->toLowerCase = "foobar"}}',
	'{{return "FOOBAR"->toUpperCase = "FOOBAR"}}',
	'{{return "FooBar"->toUpperCase = "FOOBAR"}}',
	'{{return "foobar"->toUpperCase = "FOOBAR"}}',
	'{{return "&"->htmlentities = "&amp;"}}',
	'{{return "<"->htmlentities = "&lt;"}}',
	'{{return ">"->htmlentities = "&gt;"}}',
	'{{return \'"\'->htmlentities = "&quot;"}}',
	'{{return "\'"->htmlentities = "&#039;"}}',
	'{{return "foo"->split->toJSON = ["f", "o", "o"]->toJSON}}',
	'{{return "f.o.o"->split("X")->toJSON = ["f.o.o"]->toJSON}}',
	'{{return "f.o.o"->split(".")->toJSON = ["f", "o", "o"]->toJSON}}',
	'{{return "f?+*o.o"->split("?+*")->toJSON = ["f", "o.o"]->toJSON}}',
	'{{return "f.....o.....|.....o"->split(/[.|]+/)->toJSON = ["f", "o", "o"]->toJSON}}',
	'{{return "f.....o|o"->split(/[.|]+/)->toJSON = ["f", "o", "o"]->toJSON}}',
	'{{return "f.....o|o"->split(/[|]+/)->toJSON = ["f.....o", "o"]->toJSON}}',
	'{{return "f.....o|o"->split(/[a-z]+/)->toJSON = ["", ".....", "|", ""]->toJSON}}',
	'{{return "0123456789"->charCodeAt(0) = 48}}',
	'{{return "0123456789"->charCodeAt(9) = 57}}',
	'{{return "0123456789"->charCodeAt(-1) = 57}}',
	'{{return "0123456789"->charCodeAt(309)->isUndefined->toString = "true"}}',
	'{{return "0123456789"->charCodeAt(-100)->isUndefined->toString = "true"}}',
	'{{return "0123456789"->charCodeAt("0") = 48}}',
	'{{return "0123456789"->charCodeAt("-0") = 48}}',
	'{{return "0123456789"->charCodeAt("+0") = 48}}',
	'{{return "0123456789"->charCodeAt("0x01") = 49}}',
	'{{return "0123456789"->charCodeAt("-0x01") = 57}}',
	'{{return "0123456789"->charCodeAt("+0x01") = 49}}',
	'{{return "0123456789"->charCodeAt("0b01") = 49}}',
	'{{return "0123456789"->charCodeAt("-0b01") = 57}}',
	'{{return "0123456789"->charCodeAt("+0b01") = 49}}',

	'{{return "   hey ho lets go   "->strip = "hey ho lets go"}}',
	'{{return "    \n\r\t   hey\n\r\tho\n\r\tlets\n\r\tgo    \n\r\t   "->strip = "hey\n\r\tho\n\r\tlets\n\r\tgo"}}',
	'{{return "|||||hey||||ho|||||lets||||go|||||"->strip("|") = "hey||||ho|||||lets||||go"}}',
	'{{return "|A|B|hey|AA|ho|BB|lets|CC|go|D|E|"->strip("AB|DE") = "hey|AA|ho|BB|lets|CC|go"}}',
	'{{return "|A|B|hey|AA|ho|BB|lets|CC|go|D|E|"->strip("DE|||||ABAB|DE") = "hey|AA|ho|BB|lets|CC|go"}}',
	'{{return "   hey ho lets go   "->trim = "hey ho lets go"}}',
	'{{return "    \n\r\t   hey\n\r\tho\n\r\tlets\n\r\tgo    \n\r\t   "->trim = "hey\n\r\tho\n\r\tlets\n\r\tgo"}}',
	'{{return "|||||hey||||ho|||||lets||||go|||||"->trim("|") = "hey||||ho|||||lets||||go"}}',
	'{{return "|A|B|hey|AA|ho|BB|lets|CC|go|D|E|"->trim("AB|DE") = "hey|AA|ho|BB|lets|CC|go"}}',
	'{{return "|A|B|hey|AA|ho|BB|lets|CC|go|D|E|"->trim("DE|||||ABAB|DE") = "hey|AA|ho|BB|lets|CC|go"}}',


	'{{return "   hey ho lets go   "->stripStart = "hey ho lets go   "}}',
	'{{return "    \n\r\t   hey\n\r\tho\n\r\tlets\n\r\tgo    \n\r\t   "->stripStart = "hey\n\r\tho\n\r\tlets\n\r\tgo    \n\r\t   "}}',
	'{{return "|||||hey||||ho|||||lets||||go|||||"->stripStart("|") = "hey||||ho|||||lets||||go|||||"}}',
	'{{return "|A|B|hey|AA|ho|BB|lets|CC|go|D|E|"->stripStart("AB|DE") = "hey|AA|ho|BB|lets|CC|go|D|E|"}}',
	'{{return "|A|B|hey|AA|ho|BB|lets|CC|go|D|E|"->stripStart("DE|||||ABAB|DE") = "hey|AA|ho|BB|lets|CC|go|D|E|"}}',
	'{{return "   hey ho lets go   "->trimStart = "hey ho lets go   "}}',
	'{{return "    \n\r\t   hey\n\r\tho\n\r\tlets\n\r\tgo    \n\r\t   "->trimStart = "hey\n\r\tho\n\r\tlets\n\r\tgo    \n\r\t   "}}',
	'{{return "|||||hey||||ho|||||lets||||go|||||"->trimStart("|") = "hey||||ho|||||lets||||go|||||"}}',
	'{{return "|A|B|hey|AA|ho|BB|lets|CC|go|D|E|"->trimStart("AB|DE") = "hey|AA|ho|BB|lets|CC|go|D|E|"}}',
	'{{return "|A|B|hey|AA|ho|BB|lets|CC|go|D|E|"->trimStart("DE|||||ABAB|DE") = "hey|AA|ho|BB|lets|CC|go|D|E|"}}',

	'{{return "   hey ho lets go   "->stripEnd = "   hey ho lets go"}}',
	'{{return "    \n\r\t   hey\n\r\tho\n\r\tlets\n\r\tgo    \n\r\t   "->stripEnd = "    \n\r\t   hey\n\r\tho\n\r\tlets\n\r\tgo"}}',
	'{{return "|||||hey||||ho|||||lets||||go|||||"->stripEnd("|") = "|||||hey||||ho|||||lets||||go"}}',
	'{{return "|A|B|hey|AA|ho|BB|lets|CC|go|D|E|"->stripEnd("AB|DE") = "|A|B|hey|AA|ho|BB|lets|CC|go"}}',
	'{{return "|A|B|hey|AA|ho|BB|lets|CC|go|D|E|"->stripEnd("DE|||||ABAB|DE") = "|A|B|hey|AA|ho|BB|lets|CC|go"}}',
	'{{return "   hey ho lets go   "->trimEnd = "   hey ho lets go"}}',
	'{{return "    \n\r\t   hey\n\r\tho\n\r\tlets\n\r\tgo    \n\r\t   "->trimEnd = "    \n\r\t   hey\n\r\tho\n\r\tlets\n\r\tgo"}}',
	'{{return "|||||hey||||ho|||||lets||||go|||||"->trimEnd("|") = "|||||hey||||ho|||||lets||||go"}}',
	'{{return "|A|B|hey|AA|ho|BB|lets|CC|go|D|E|"->trimEnd("AB|DE") = "|A|B|hey|AA|ho|BB|lets|CC|go"}}',
	'{{return "|A|B|hey|AA|ho|BB|lets|CC|go|D|E|"->trimEnd("DE|||||ABAB|DE") = "|A|B|hey|AA|ho|BB|lets|CC|go"}}',
	'{{return "    \n\r\t   hey\n\r\tho\n\r\tlets\n\r\tgo    \n\r\t   "->trimEnd->trimStart = "hey\n\r\tho\n\r\tlets\n\r\tgo"}}',
	'{{return "    \n\r\t   hey\n\r\tho\n\r\tlets\n\r\tgo    \n\r\t   "->trimStart->trimEnd = "hey\n\r\tho\n\r\tlets\n\r\tgo"}}',
	'{{return "    \n\r\t   hey\n\r\tho\n\r\tlets\n\r\tgo    \n\r\t   "->stripEnd->trimStart = "hey\n\r\tho\n\r\tlets\n\r\tgo"}}',
	'{{return "    \n\r\t   hey\n\r\tho\n\r\tlets\n\r\tgo    \n\r\t   "->stripStart->trimEnd = "hey\n\r\tho\n\r\tlets\n\r\tgo"}}',



	'{{return "string"->slice(3) = "ing"}}',
	'{{return "string"->slice = "string"}}',
	'{{return "string"->slice("NAN")->isUndefined->toString = "true"}}',
	'{{return "string"->slice(1, "NAN")->isUndefined->toString = "true"}}',
	'{{return "string"->slice(0, 10000, "NAN") = "string"}}',
	'{{return "string"->slice(1, 10000, "NAN") = "tring"}}',
	'{{return "string"->slice(1, -1) = "trin"}}',
	'{{return "string"->reverse = "gnirts"}}',
	'{{return ""->reverse = ""}}',
	'{{return "A"->reverse = "A"}}',
	'{{return "Ab"->reverse = "bA"}}',
	'{{return "string"->replace(123) = "string"}}',
	'{{return "string"->replace = "string"}}',
	'{{return "istringi"->replace("i", "[]") = "[]str[]ng[]"}}',
	'{{return "[a-z]+str[a-z]+ng[a-z]+"->replace("[a-z]+", "[]") = "[]str[]ng[]"}}',
	'{{return "string"->replace(/[a-z]+/, "A") = "A"}}',
	'{{return "stRiNg"->replace(/[a-z]+/, "A") = "ARiNg"}}',
	'{{return "stRiNg"->replace(/[a-z]+/g, "A") = "ARANA"}}',
	'{{return "string"->replace(/[a-z]/g, letter => letter->toUpperCase) = "STRING"}}',
	'{{#HEY#}}->isString->toString = "true"',
	'{{#{{2 * 2}}#}} = "[29,[11,2,2]]"',
	`
		{{var x = {{#
			{{2 * 2}}
		#}}}}
		{{return x->eval->trim = "4"}}
	`,
	`
		{{var x = {{#
			{{2 * 2}}
		#}}}}
		{{return x->eval->strip = "4"}}
	`,
	`
		{{var x = {{#
			{{this->toJSON}}
		#}}}}
		{{return x->eval([1, 2, 3])->strip = "[1,2,3]"}}
	`,
	`
		{{var x = {{#
			{{this->toJSON}}
		#}}}}
		{{return x->eval([1, 2, 3])->trim = "[1,2,3]"}}
	`,
	`
		{{return {{#
			HEY-{{this->toJSON}}-HO
		#}}->eval([1, 2, 3])->strip = "HEY-[1,2,3]-HO"}}
	`,
	`
		{{return {{#
			HEY-{{this->toJSON}}-HO
		#}}->eval([1, 2, 3])->trim = "HEY-[1,2,3]-HO"}}
	`,
	'{{return "string"()->isUndefined->toString = "true"}}',
	'{{return "true_string_false"->startsWith->toString = "false"}}',
	'{{return "true_string_false"->endsWith->toString = "false"}}',
	'{{return "true_string_false"->startsWith(true)}}',
	'{{return "true_string_false"->endsWith(false)}}',
	'{{return "true_string_false"->startsWith("true_")->toString = "true"}}',
	'{{return "true_string_false"->startsWith("false_")->toString = "false"}}',
	'{{return "true_string_false"->endsWith("_false")->toString = "true"}}',
	'{{return "true_string_false"->endsWith("_true")->toString = "false"}}',
	'{{return "true_string_false"->startsWith(1)->toString = "false"}}',
	'{{return "true_string_false"->endsWith(1)->toString = "false"}}',
	'{{return "true_string_false"->startsWith(0)->toString = "false"}}',
	'{{return "true_string_false"->endsWith(0)->toString = "false"}}',


	'{{return "true_string_false"->includes->toString = "false"}}',
	'{{return "true_string_false"->includes()->toString = "false"}}',
	'{{return "true_string_false"->includes("string")->toString = "true"}}',
	'{{return "true_string_false"->includes("")->toString = "true"}}',
	'{{return "true_string_false"->includes(" ")->toString = "false"}}',
	'{{return "true_string_false"->includes("???")->toString = "false"}}',
	'{{return "true_string_false"->includes("_")->toString = "true"}}',
	'{{return "true_string_false"->includes("true")->toString = "true"}}',
	'{{return "true_string_false"->includes("false")->toString = "true"}}',
	'{{return "true_string_false"->includes("true_")->toString = "true"}}',
	'{{return "true_string_false"->includes("_false")->toString = "true"}}',
	'{{return "true_string_false"->includes("_string_")->toString = "true"}}',
	'{{return "true_string_false"->includes(true)->toString = "true"}}',
	'{{return "true_string_false"->includes(false)->toString = "true"}}',
	'{{return "true_string_false"->includes(1)->toString = "false"}}',
	'{{return "true_string_false"->includes(0)->toString = "false"}}',
	'{{return "1_string_0"->includes(1)->toString = "true"}}',
	'{{return "1_string_0"->includes(0)->toString = "true"}}',
	'{{return "1_string_0"->includes(true)->toString = "false"}}',
	'{{return "1_string_0"->includes(false)->toString = "false"}}',
	'{{return "1_string_0"->includes(1, "0")->toString = "true"}}',
	'{{return "1_string_0"->includes(1, "1")->toString = "false"}}',
	'{{return "1_st1ring_0"->includes(1, "1")->toString = "true"}}',
	'{{return "1_st1ring_0"->includes(1, "x1")->toString = "false"}}',
	'{{return "1_st1ring_0"->includes(1, "0x00")->toString = "true"}}',
	'{{return "1_st1ring_0"->includes("1_", 0)->toString = "true"}}',
	'{{return "1_st1_ring_0"->includes("1_", 1)->toString = "true"}}',
	'{{return "1_st1_ring_0"->includes("1_", 4)->toString = "true"}}',
	'{{return "1_st1_ring_0"->includes("1_", 5)->toString = "false"}}',
	'{{return "1_st1_ring_0"->includes("_0", -1)->toString = "false"}}',
	'{{return "1_st1_ring_0"->includes("_0", -2)->toString = "true"}}',
	'{{return "1_st1_ring_0"->includes("_0", 3000)->toString = "false"}}',
	'{{return "1_st1_ring_0"->includes("_0", -1000)->toString = "true"}}',
	'{{return "1_st1_ring_0"->includes("1_", -1000)->toString = "true"}}',
	'{{return "true_string_false"->contains->toString = "false"}}',
	'{{return "true_string_false"->contains()->toString = "false"}}',
	'{{return "true_string_false"->contains("string")->toString = "true"}}',
	'{{return "true_string_false"->contains("")->toString = "true"}}',
	'{{return "true_string_false"->contains(" ")->toString = "false"}}',
	'{{return "true_string_false"->contains("???")->toString = "false"}}',
	'{{return "true_string_false"->contains("_")->toString = "true"}}',
	'{{return "true_string_false"->contains("true")->toString = "true"}}',
	'{{return "true_string_false"->contains("false")->toString = "true"}}',
	'{{return "true_string_false"->contains("true_")->toString = "true"}}',
	'{{return "true_string_false"->contains("_false")->toString = "true"}}',
	'{{return "true_string_false"->contains("_string_")->toString = "true"}}',
	'{{return "true_string_false"->contains(true)->toString = "true"}}',
	'{{return "true_string_false"->contains(false)->toString = "true"}}',
	'{{return "true_string_false"->contains(1)->toString = "false"}}',
	'{{return "true_string_false"->contains(0)->toString = "false"}}',
	'{{return "1_string_0"->contains(1)->toString = "true"}}',
	'{{return "1_string_0"->contains(0)->toString = "true"}}',
	'{{return "1_string_0"->contains(true)->toString = "false"}}',
	'{{return "1_string_0"->contains(false)->toString = "false"}}',
	'{{return "1_string_0"->contains(1, "0")->toString = "true"}}',
	'{{return "1_string_0"->contains(1, "1")->toString = "false"}}',
	'{{return "1_st1ring_0"->contains(1, "1")->toString = "true"}}',
	'{{return "1_st1ring_0"->contains(1, "x1")->toString = "false"}}',
	'{{return "1_st1ring_0"->contains(1, "0x00")->toString = "true"}}',
	'{{return "1_st1ring_0"->contains("1_", 0)->toString = "true"}}',
	'{{return "1_st1_ring_0"->contains("1_", 1)->toString = "true"}}',
	'{{return "1_st1_ring_0"->contains("1_", 4)->toString = "true"}}',
	'{{return "1_st1_ring_0"->contains("1_", 5)->toString = "false"}}',
	'{{return "1_st1_ring_0"->contains("_0", -1)->toString = "false"}}',
	'{{return "1_st1_ring_0"->contains("_0", -2)->toString = "true"}}',
	'{{return "1_st1_ring_0"->contains("_0", 3000)->toString = "false"}}',
	'{{return "1_st1_ring_0"->contains("_0", -1000)->toString = "true"}}',
	'{{return "1_st1_ring_0"->contains("1_", -1000)->toString = "true"}}',
	'{{return "0"->repeat = "0"}}',
	'{{return "0"->repeat("FOO") = "0"}}',
	'{{return "0"->repeat("0x00") = "0"}}',
	'{{return "0"->repeat(0) = "0"}}',
	'{{return "0"->repeat(1) = "0"}}',
	'{{return "0"->repeat(undefined) = "0"}}',
	'{{return "0"->repeat(false) = "0"}}',
	'{{return "0"->repeat(-1) = "0"}}',
	'{{return "0"->repeat(true) = "0"}}',
	'{{return "0"->repeat(2) = "00"}}',
	'{{return "0"->repeat("2") = "00"}}',
	'{{return "0"->repeat("0b10") = "00"}}',
	'{{return "0"->repeat("0b11") = "000"}}',
	'{{return "AB_"->repeat("0b11") = "AB_AB_AB_"}}',,
	'{{return "."->repeat(300)->length = 300}}',
	'{{return ".."->repeat(300)->length = 600}}',

	"{{return 'abc'->padStart = 'abc'}}",
	"{{return 'abc'->padStart(-1) = 'abc'}}",
	"{{return 'abc'->padStart(0) = 'abc'}}",
	"{{return 'abc'->padStart(3) = 'abc'}}",
	"{{return 'a'->padStart(-1) = 'a'}}",
	"{{return 'a'->padStart(0) = 'a'}}",
	"{{return 'a'->padStart(false) = 'a'}}",
	"{{return 'a'->padStart(1) = 'a'}}",
	"{{return 'a'->padStart(2) = ' a'}}",
	"{{return 'abc'->padStart(4) = ' abc'}}",
	"{{return 'abc'->padStart(10) = '       abc'}}",
	"{{return 'abc'->padStart(10, 'foo') = 'foofoofabc'}}",
	"{{return 'abc'->padStart(6, '123465') = '123abc'}}",
	"{{return 'abc'->padStart(8, '0') = '00000abc'}}",
	"{{return 'abc'->padStart(1) = 'abc'}}",
	"{{return 'abc'->padStart('10') = '       abc'}}",
	"{{return 'abc'->padStart('10', 'foo') = 'foofoofabc'}}",
	"{{return 'abc'->padStart('6', '123465') = '123abc'}}",
	"{{return 'abc'->padStart('8', '0') = '00000abc'}}",
	"{{return 'abc'->padStart('1') = 'abc'}}",
	"{{return 'abc'->padStart(true) = 'abc'}}",
	"{{return '1'->padStart(4, true) = 'tru1'}}",
	"{{return '1'->padStart(3, true) = 'tr1'}}",
	"{{return '1'->padStart(2, true) = 't1'}}",
	"{{return '1'->padStart(1, true) = '1'}}",
	"{{return '1'->padStart(4, 0x02) = '2221'}}",
	"{{return '1'->padStart(3, 0x02) = '221'}}",
	"{{return '1'->padStart(2, 0x02) = '21'}}",
	"{{return '1'->padStart(1, 0x02) = '1'}}",
	"{{return range(0, 9)->map(i => i->toString->padStart(3, '0'))->join('-') = '000-001-002-003-004-005-006-007-008-009'}}",

	"{{return 'abc'->padEnd = 'abc'}}",
	"{{return 'abc'->padEnd(-1) = 'abc'}}",
	"{{return 'abc'->padEnd(0) = 'abc'}}",
	"{{return 'abc'->padEnd(3) = 'abc'}}",
	"{{return 'a'->padEnd(-1) = 'a'}}",
	"{{return 'a'->padEnd(0) = 'a'}}",
	"{{return 'a'->padEnd(false) = 'a'}}",
	"{{return 'a'->padEnd(1) = 'a'}}",
	"{{return 'a'->padEnd(2) = 'a '}}",
	"{{return 'abc'->padEnd(4) = 'abc '}}",
	"{{return 'abc'->padEnd(10) = 'abc       '}}",
	"{{return 'abc'->padEnd(10, 'foo') = 'abcfoofoof'}}",
	"{{return 'abc'->padEnd(6, '123465') = 'abc123'}}",
	"{{return 'abc'->padEnd(8, '0') = 'abc00000'}}",
	"{{return 'abc'->padEnd(1) = 'abc'}}",
	"{{return 'abc'->padEnd('10') = 'abc       '}}",
	"{{return 'abc'->padEnd('10', 'foo') = 'abcfoofoof'}}",
	"{{return 'abc'->padEnd('6', '123465') = 'abc123'}}",
	"{{return 'abc'->padEnd('8', '0') = 'abc00000'}}",
	"{{return 'abc'->padEnd('1') = 'abc'}}",
	"{{return 'abc'->padEnd(true) = 'abc'}}",
	"{{return '1'->padEnd(4, true) = '1tru'}}",
	"{{return '1'->padEnd(3, true) = '1tr'}}",
	"{{return '1'->padEnd(2, true) = '1t'}}",
	"{{return '1'->padEnd(1, true) = '1'}}",
	"{{return '1'->padEnd(4, 0x02) = '1222'}}",
	"{{return '1'->padEnd(3, 0x02) = '122'}}",
	"{{return '1'->padEnd(2, 0x02) = '12'}}",
	"{{return '1'->padEnd(1, 0x02) = '1'}}",
	"{{return range(0, 9)->map(i => i->toString->padEnd('0b11', false))->join('-') = '0fa-1fa-2fa-3fa-4fa-5fa-6fa-7fa-8fa-9fa'}}",


	"{{return ''->indexOf = -1}}",
	"{{return ''->lastIndexOf = -1}}",
	"{{return 'string'->indexOf = -1}}",
	"{{return 'string'->lastIndexOf = -1}}",

	"{{return 'abtruedef'->indexOf('g') = -1}}",
	"{{return 'abtruedef'->indexOf('a') = 0}}",
	"{{return 'abtruedef'->indexOf('b') = 1}}",
	"{{return 'abtruedef'->indexOf('t') = 2}}",
	"{{return 'abtruedef'->indexOf('true') = 2}}",
	"{{return 'abtruedef'->indexOf(true) = 2}}",
	"{{return 'abtruxdef'->indexOf('true') = -1}}",
	"{{return 'abtruedef'->indexOf('a', 1) = -1}}",
	"{{return 'abtruedef'->indexOf('b', 1) = 1}}",
	"{{return 'abtruedef'->indexOf('b', 2) = -1}}",
	"{{return 'abtruedef'->indexOf('t', 2) = 2}}",
	"{{return 'abtruedef'->indexOf('t', 3) = -1}}",
	"{{return 'abtruedef'->indexOf('true', 2) = 2}}",
	"{{return 'abtruxdef'->indexOf('true', 3) = -1}}",
	"{{return 'abtruedef'->indexOf(true, 2) = 2}}",
	"{{return 'abtruxdef'->indexOf(true, 3) = -1}}",
	"{{return 'abtruedef'->indexOf(true, '0b10') = 2}}",
	"{{return 'abtruedef'->indexOf(true, '0b11') = -1}}",
	"{{return 'The quick brown fox jumps over the lazy dog. If the dog barked, was it really lazy?'->indexOf('dog') = 40}}",
	"{{return 'The quick brown fox jumps over the lazy dog. If the dog barked, was it really lazy?'->indexOf('dog', 40) = 40}}",
	"{{return 'The quick brown fox jumps over the lazy dog. If the dog barked, was it really lazy?'->indexOf('dog', 41) = 52}}",
	"{{return 'The quick brown fox jumps over the lazy dog. If the dog barked, was it really lazy?'->indexOf('dog', 52) = 52}}",
	"{{return 'The quick brown fox jumps over the lazy dog. If the dog barked, was it really lazy?'->indexOf('dog', 53) = -1}}",
	"{{return 'hello world'->indexOf('') = 0}}",
	"{{return 'hello world'->indexOf('', 0) = 0}}",
	"{{return 'hello world'->indexOf('', 3) = 3}}",
	"{{return 'hello world'->indexOf('', 8) = 8}}",
	"{{return 'hello world'->indexOf('', 11) = 11}}",
	"{{return 'hello world'->indexOf('', 13) = 11}}",
	"{{return 'hello world'->indexOf('', 12) = 11}}",
	"{{return 'Blue Whale'->indexOf('Blue') = 0}}",
	"{{return 'Blue Whale'->indexOf('Blute') = -1}}",
	"{{return 'Blue Whale'->indexOf('Whale', 0) = 5}}",
	"{{return 'Blue Whale'->indexOf('Whale', 5) = 5}}",
	"{{return 'Blue Whale'->indexOf('Whale', 7) = -1}}",
	"{{return 'Blue Whale'->indexOf('') = 0}}",
	"{{return 'Blue Whale'->indexOf('', 9) = 9}}",
	"{{return 'Blue Whale'->indexOf('', 10) = 10}}",
	"{{return 'Blue Whale'->indexOf('', 11) = 10}}",
	"{{return 'Blue Whale'->indexOf('blue') = -1}}",
	"{{return ('Blue Whale'->indexOf('Blue') != -1)->toString = 'true'}}",
	"{{return ('Blue Whale'->indexOf('Bloe') != -1)->toString = 'false'}}",
	"{{return 'Brave new world'->indexOf('w') = 8}}",
	"{{return 'Brave new world'->indexOf('new') = 6}}",
	"{{return 'brie, pepper jack, cheddar'->indexOf('cheddar') = 19}}",
	"{{return 'Brie, Pepper Jack, Cheddar'->indexOf('cheddar') = -1}}",


	"{{return 'The quick brown fox jumps over the lazy dog. If the dog barked, was it really lazy?'->lastIndexOf('dog') = 52}}",
	"{{return 'The quick brown fox jumps over the lazy dog. If the dog barked, was it really lazy?'->lastIndexOf('dog', 52) = 52}}",
	"{{return 'The quick brown fox jumps over the lazy dog. If the dog barked, was it really lazy?'->lastIndexOf('dog', 51) = 40}}",
	"{{return 'The quick brown fox jumps over the lazy dog. If the dog barked, was it really lazy?'->lastIndexOf('dog', 40) = 40}}",
	"{{return 'The quick brown fox jumps over the lazy dog. If the dog barked, was it really lazy?'->lastIndexOf('dog', 39) = -1}}",


	"{{return 'canal'->lastIndexOf('a') = 3}}",
	"{{return 'canal'->lastIndexOf('a', 2) = 1}}",
	"{{return 'canal'->lastIndexOf('a', 0) = -1}}",
	"{{return 'canal'->lastIndexOf('x') = -1}}",
	"{{return 'canal'->lastIndexOf('c', -5) = 0}}",
	"{{return 'canal'->lastIndexOf('c', 0) = 0}}",
	"{{return 'canal'->lastIndexOf('') = 5}}",
	"{{return 'canal'->lastIndexOf('', 2) = 2}}",
	"{{return 'Blue Whale, Killer Whale'->lastIndexOf('blue') = -1}}",
	"{{return 'Brave new world'->lastIndexOf('w') = 10}}",
	"{{return 'Brave new world'->lastIndexOf('new') = 6}}"
];
