module.exports = [
	`{{return []->isArray->toString = "true"}}`,
	`{{return undefined->toArray->length = 1}}`,
	`{{return null->toArray->length = 1}}`,
	`{{return "string"->toArray->length = 1}}`,
	`{{return true->toArray->length = 1}}`,
	`{{return false->toArray->length = 1}}`,
	`{{return 10->toArray->length = 1}}`,
	`{{return /re/->toArray->length = 1}}`,
	`{{return [1, 2, 3]->toArray->length = 3}}`,
	`{{return (=>10)->toArray->length = 1}}`,
	`{{return getDate->toArray->length != 1}}`,
	`{{return undefined->toArray[0]->isUndefined}}`,
	`{{return undefined->toArray()[0]->isUndefined}}`,
	`{{return null->toArray[0]->isNull}}`,
	`{{return null->toArray()[0]->isNull}}`,
	`{{return "string"->toArray[0]->isString}}`,
	`{{return "string"->toArray()[0]->isString}}`,
	`{{return true->toArray[0]->isBoolean}}`,
	`{{return true->toArray()[0]->isBoolean}}`,
	`{{return false->toArray[0]->isBoolean}}`,
	`{{return false->toArray()[0]->isBoolean}}`,
	`{{return 10->toArray[0]->isNumber}}`,
	`{{return 10->toArray()[0]->isNumber}}`,
	`{{return /ref/->toArray[0]->isRegExp}}`,
	`{{return /ref/->toArray()[0]->isRegExp}}`,
	`{{return [3, 2, 1]->toArray[0] = 3}}`,
	`{{return [3, 2, 1]->toArray()[0] = 3}}`,
	`{{return (=>10)->toArray[0]->isMacro}}`,
	`{{return (=>10)->toArray()[0]->isMacro}}`,
];
